export const generatePreferencesHtml = (rows: any[]) => {
  const tableRows = rows.map(row => `
    <tr>
      <td>${row.full_name}</td>
      <td>
        <span class="badge ${row.ceremony_choice === 'oath' ? 'badge-oath' : 'badge-affirmation'}">
          ${row.ceremony_choice.toUpperCase()}
        </span>
      </td>
      <td>${row.religious_text || '<em>N/A (Non-religious)</em>'}</td>
    </tr>
  `).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; padding: 40px; color: #333; line-height: 1.5; }
        .header { border-bottom: 3px solid #C9922A; margin-bottom: 30px; padding-bottom: 20px; }
        .title { font-size: 22pt; color: #1a1c1e; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
        .meta { color: #666; font-size: 10pt; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #1a1c1e; color: #C9922A; padding: 12px; text-align: left; font-size: 10pt; text-transform: uppercase; }
        td { padding: 12px; border-bottom: 1px solid #eee; font-size: 11pt; }
        .badge { padding: 4px 10px; border-radius: 4px; font-size: 8pt; font-weight: bold; display: inline-block; }
        .badge-oath { background: #fcf9f2; color: #C9922A; border: 1px solid #C9922A; }
        .badge-affirmation { background: #e8f5e9; color: #2e7d32; border: 1px solid #2e7d32; }
        .footer { margin-top: 50px; font-size: 8pt; color: #aaa; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">Swearing-In Preferences Report</div>
        <div class="meta">Office of the Registrar High Court | Generated: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</div>
      </div>
      <table>
        <thead>
          <tr>
            <th>Judicial Officer</th>
            <th>Ceremony Choice</th>
            <th>Sacred Text / Reference</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
      <div class="footer">
        This is an official document generated by the Judicial Onboarding Portal.
      </div>
    </body>
    </html>
  `;
};